name: Pipe Unichain Sepolia metrics to Dune (from Allium Snowflake)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Log directory structure
        run: |
          pwd
          ls -R

      - name: Debug Environment Variables
        run: |
          echo "SNOWFLAKE_ACCOUNT: $SNOWFLAKE_ACCOUNT"
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

      - name: Decode Private Key
        run: echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_DER }}" | base64 --decode > rsa_key.der

      - name: Set Private Key Permissions
        run: chmod 600 rsa_key.der

      - name: pip requirements
        run: pip install -r requirements.txt

      - name: Pipe Unichain Sepolia metrics to Dune
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_PRIVATE_KEY_PATH: rsa_key.der
        run: python -u scripts/pipe_unichain_testnet_data.py
