name: Pipe Unichain Sepolia metrics to Dune (from Allium Snowflake)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Log directory structure
        run: |
          pwd
          ls -R

      - name: pip requirements
        run: pip install -r requirements.txt

      - name: Pipe Unichain Sepolia metrics to Dune
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: python -u scripts/pipe_unichain_testnet_data.py
